Refactor/controllers
jpsandovaln/PROG102-FileConversion pull request #17
Opened 2020-09-11 02:47 UTC by JhordanSoto

refactoring all the controllers

2020-09-11 15:06 UTC, MirkoFer-622 approved these changes

2020-09-11 16:00 UTC, roht0515 commented on src/main/java/org/fundacionjala/converter/controller/AudioController.java
> +       //     result = exec.executer(audioParameter);
delete this line if it is not necessary

2020-09-11 16:01 UTC, roht0515 commented on src/main/java/org/fundacionjala/converter/controller/ImageController.java
> +            //result = exec.executer(imageParameter);
delete comments if these are not necessary

2020-09-11 16:02 UTC, roht0515 commented on src/test/java/org/fundacionjala/converter/ApplicationTests.java
> +    }*/
delete the comments please

2020-09-11 16:04 UTC, roht0515 requested changes
please, check the comments that i left on the PR

2020-09-12 02:13 UTC, maryangela commented
please solve the conflicts

2020-09-12 15:58 UTC, JhordanSoto commented on src/main/java/org/fundacionjala/converter/controller/AudioController.java
> +       //     result = exec.executer(audioParameter);
those lines are necessary because it will e discomented when the model is ready

2020-09-12 15:58 UTC, JhordanSoto commented on src/main/java/org/fundacionjala/converter/controller/ImageController.java
> +            //result = exec.executer(imageParameter);
those lines are necessary because it will e discomented when the model is ready

2020-09-12 15:58 UTC, JhordanSoto commented on src/test/java/org/fundacionjala/converter/ApplicationTests.java
> +    }*/
those lines are necessary because it will e discomented when the model is ready

2020-09-12 16:48 UTC, Laura4lilavati approved these changes

2020-09-12 19:36 UTC, julia-jpg approved these changes

2020-09-13 16:41 UTC, starsaminf approved these changes

2020-09-13 22:40 UTC, merged