Refactor model structure
jpsandovaln/PROG102-FileConversion pull request #19
Opened 2020-09-11 14:14 UTC by starsaminf

2020-09-11 14:24 UTC, Laura4lilavati commented on src/main/java/org/fundacionjala/converter/model/configPath/ConfigPath.java
> +  public String getToolExtactor() {
Please can you change the name of the method to getToolExtractText()?

2020-09-11 14:25 UTC, julia-jpg approved these changes

2020-09-11 14:26 UTC, Laura4lilavati commented on src/main/java/org/fundacionjala/converter/model/configPath/ConfigPath.java
> +  public String getToolVideo() {
Please can you change the name of the method to getVideoTool?

2020-09-11 14:27 UTC, Laura4lilavati commented on src/main/java/org/fundacionjala/converter/model/configPath/ConfigPath.java
> +  public String getToolAudio() {
Please can you change the name of the method to getAudioTool? or is it possible to delete this method because the tool used in Audio and Video is the same?

2020-09-11 14:28 UTC, Laura4lilavati commented on src/main/java/org/fundacionjala/converter/model/configPath/ConfigPath.java
> +  public String getToolMetaDataExtractor() {
Please can you change the name of the method to getMetaDataExtractorTool?

2020-09-11 14:30 UTC, Laura4lilavati commented on src/main/java/org/fundacionjala/converter/executor/Executor.java
> +    StringBuilder outPut = new StringBuilder();
Please can you change the name of variable: outPut to output in lowercase?

2020-09-11 14:31 UTC, Laura4lilavati commented on src/main/java/org/fundacionjala/converter/executor/Executor.java
> +  private boolean debugOutPut;
please can you change the name of variable to debugOutput?

2020-09-11 14:31 UTC, Laura4lilavati commented on src/main/java/org/fundacionjala/converter/executor/Executor.java
> +  public void setDebugOutPut(final boolean debugOutPut) {
please can you change the name of method to setDebugOutput?

2020-09-11 14:39 UTC, Laura4lilavati commented on src/main/java/org/fundacionjala/converter/model/parameter/ocr/OcrParameter.java
> +public class OcrParameter extends ModelParameter {
Please can you change the name of this class to ExtractTextParameter? Because it is a more descriptive name of what this class do.

2020-09-11 14:40 UTC, MirkoFer-622 commented on src/main/java/org/fundacionjala/converter/model/configPath/ConfigPath.java
> +  public String getToolVideo() {
Even, I think that Video and Audio Tools is the same, so it woud be getVideoAndAudioTool( )!

2020-09-11 14:59 UTC, MirkoFer-622 commented on src/main/java/org/fundacionjala/converter/model/parameter/ModelParameter.java
> +
Its needed those setters? What if only set attributes at its constructor?

2020-09-11 15:02 UTC, MirkoFer-622 requested changes
Please consider use constructors instead setters.

2020-09-11 15:32 UTC, starsaminf commented on src/main/java/org/fundacionjala/converter/model/configPath/ConfigPath.java
> +  public String getToolVideo() {
I think what "And" is not necessary.

2020-09-11 15:34 UTC, starsaminf commented on src/main/java/org/fundacionjala/converter/model/configPath/ConfigPath.java
> +  public String getToolAudio() {
Thks but It's not necessary, I deleted this method

2020-09-11 15:34 UTC, starsaminf commented on src/main/java/org/fundacionjala/converter/model/configPath/ConfigPath.java
> +  public String getToolMetaDataExtractor() {
Ok

2020-09-11 15:57 UTC, starsaminf commented on src/main/java/org/fundacionjala/converter/model/parameter/ModelParameter.java
> +
Thks

2020-09-11 16:06 UTC, roht0515 commented on src/main/java/org/fundacionjala/converter/executor/Executor.java
> +
i think that this line is not necessary

2020-09-11 16:07 UTC, roht0515 commented on src/main/java/org/fundacionjala/converter/commons/ChecksumMD5.java
> +            while ((nread = fis.read(buffer)) != -1) {
please, can you put a descritive name for this attribute "nread"

2020-09-11 16:08 UTC, roht0515 commented on src/main/java/org/fundacionjala/converter/commons/ChecksumMD5.java
> +
i think that this blank line is not necessary

2020-09-11 19:32 UTC, Laura4lilavati commented on src/main/java/org/fundacionjala/converter/model/configPath/ConfigPath.java
> +  public String getToolVideo() {
Do you consider to change the name of this method to getMultimediaTool?

2020-09-12 00:48 UTC, starsaminf commented on src/main/java/org/fundacionjala/converter/executor/Executor.java
> +
I think that this line is necessary becase thw code is more friendly

2020-09-12 01:53 UTC, Laura4lilavati approved these changes

2020-09-12 01:53 UTC, JhordanSoto commented on src/main/java/org/fundacionjala/converter/model/commons/ChecksumMD5.java
> +            while ((nread = fis.read(buffer)) != -1) {
you can use Constant instead of magic numbers

2020-09-12 01:56 UTC, roht0515 approved these changes

2020-09-12 01:58 UTC, eli7890 approved these changes

2020-09-12 01:58 UTC, merged