Basic controller audio
jpsandovaln/PROG102-FileConversion pull request #25
Opened 2020-09-16 22:11 UTC by julia-jpg

create a endpoint to controller audio

2020-09-16 22:54 UTC, starsaminf requested changes

2020-09-16 22:54 UTC, starsaminf commented on src/main/java/org/fundacionjala/converter/controller/AudioController.java
> +   }
I think what it is code repetitive

2020-09-17 13:10 UTC, starsaminf approved these changes

2020-09-17 13:27 UTC, MirkoFer-622 commented on src/main/java/org/fundacionjala/converter/controller/AudioController.java
> +        modelParameter.setOutputFile("storage/convertedFiles");
You should call this path instancing a CofigPath object, plese not hard-coding it.

2020-09-17 13:29 UTC, MirkoFer-622 commented on src/main/java/org/fundacionjala/converter/controller/request/RequestAudioParameter.java
> +    private  boolean isMetadata = false;
Please, correct blank spaces.

2020-09-17 13:31 UTC, MirkoFer-622 commented on src/main/java/org/fundacionjala/converter/executor/Executor.java
> +    System.out.println(output);
Please, avoid to push debugging code lines.

2020-09-17 13:32 UTC, MirkoFer-622 reviewed
Please, could you review my comments?

2020-09-17 13:40 UTC, maryangela approved these changes

2020-09-17 13:40 UTC, maryangela commented on src/main/java/org/fundacionjala/converter/controller/AudioController.java
> +
please delete this blank line

2020-09-17 13:40 UTC, maryangela commented on src/main/java/org/fundacionjala/converter/executor/Executor.java
> +    System.out.println(command);
please delete this line

2020-09-17 13:40 UTC, maryangela commented on src/main/java/org/fundacionjala/converter/executor/Executor.java
> +    //System.out.println(command.get(command.size() - 1));
please delete this line

2020-09-17 13:47 UTC, merged